### ISSUE TITLE
FIX tab counter numbers are wrong

### ISSUE THREAD

**Issue by allanlaal** [fero8/chrome-tab-counter#2]
## use case:

open up a new chrome window for a website with some links
open 10 links from that site
detach the original tab and close the window with the other tabs you just opened

## expected result:

tab counter decrements by 10

## actual result:

tab counter decrements by 1, sometimes 0

## notes:

this is a random use case, I'm sure there are many. I've been using this parallel with "Tab Count" and "Tab Counter" for months with hundreds of tabs open at a time and probably thousands of tabs opened during the uptime of Chrome (I have to kill it weekly as it memfloods like crazy). Only "Tab Count" reports the correct open tabs number (currently showing 149), both "Tab Counter" and this ("Chrome Tab Counter") drift off (currently both showing 975)

**Comment by fero8** [comment]
I am not able to reproduce this, tab count do increase and decrease whenever a tab or window is opened/closed.
